### ISSUE TITLE
Move as many hooks to push instead of callout

### ISSUE THREAD

**Issue by bmeck** [tc39/proposal-compartments#2]
things like time zone and locale can likely be left as a push based configuration of the compartment rather than a hook that is called on all operations. This would change:

```ts
{
  // e.g.: 'fr-FR' - Affects appropriate ECMA-402 APIs within Compartment
  localeHook(): string; 
  // This is important to be able to override for deterministic testing and such
  localTZAHook(): string;
}
```

To not be part of the hooks bag, but instead to method on Compartment instances:

```ts
{
  get locale(): string;
  set locale(string);

  get timeZone(): string;
  set timeZone(string);
}
```

Likewise, it might make more sense for a register function instead of `isDirectEvalHook`:

```ts
{
  registerDirectEval(fn): void;
}
```

IDK if we ever want to unregister direct eval functions...

**Comment by bmeck** [comment]
@syg I don't think any of the other hooks are able to be moved to this kind of push notification, but does the above make sense regarding your concerns about adding places where callouts could occur? Trying to make sure I'm on the right track. Node already does have callouts to JS in all but `canCompileHook`, but it doesn't look like that is restricted to not run JS (at least in V8).

**Comment by Jack-Works** [comment]
This proposal has been narrowed to focus on module loading, so those hooks are removed as weel.
