### ISSUE TITLE
Clarify behavioral propagation across call sites

### ISSUE THREAD

**Issue by bmeck** [tc39/proposal-compartments#3]
Various hooks in the spec are unclear on how they would propagate given Compartments.

Consider:

```mjs
// in en-CA
const fn = compartmentA.evaluate(`${
  function (d) { return (1234).toLocaleString(); }
}`);
// in fr-CA
compartmentB.evaluate(`function run(fn) { return fn(); }`)

// true for sharing intrinsics
compartmentA.evaluate(`Number`) === compartmentB.evaluate(`Number`);
```

1. If compartments cause all the intrinsics with host behavior to get data from their callsite, the result would be based upon `en-CA`. This would require potentially more data lookups for Date/Locale operations.
2. If compartments cause the first execution context to be the propagation of data, the result would be `fr-CA`. This would be VERY surprising to my experience and might not help if there is a wrapper around a callsite such as a test harness.
3. It might be the case that compartments are not the right layer to configure some of these non-callsite based APIs. This might be a very limiting result, as if they are done on a Realm level intrinsics could not be shared. This might for a more clear distinction on what should be configurable and what is not reasonably configurable.

Host specific behavior/hooks like `import()`/direct eval/debugger are explicitly callsite based, and are not problematic like these features of Time/Locale are. Some testing does show that Locale is not stable across ticks, so `1` is to some extent possible with a rewriter; however, changing time zone/locale appears to be costly to many implementations and not implemented in current browsers as changeable in a single tick.

**Comment by bmeck** [comment]
@codehag the above might be a clarification that you find useful. Per call site vs per intrinsic instance (such as `Number.prototype.toLocaleString`) behavior. I'd expect this issue specifically to be a of interest when trying to compare Realms and Compartments. Ideally from my viewpoint we could go with per call site for likely a wider variety of things than currently is done, but I do understand this likely makes an extra level of indirection to perform the lookup for these APIs that might be undesirable.

**Comment by Jack-Works** [comment]
This proposal has been narrowed to focus on module loading, so those hooks are removed as weel.
