### ISSUE TITLE
Cannot use '*' to represent namespace import/export

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-compartments#56]
See https://github.com/tc39/ecma262/pull/2154/

**Comment by kriskowal** [comment]
I do not see how that conclusion follows from https://github.com/tc39/ecma262/pull/2154.

Node.js 18 behavior is consistent with the premise, though:

https://gist.github.com/kriskowal/0df790b94fb201162e77035cbe00c48b

May I phone @bmeck for verification?

This being the case, we’ll need a new binding form like `{ importAll: true, as?: string, from: string }` or a sentinel value, `{ import: null, as?: string, from: string }`.

I strongly favor a JSON serializable form, so I’d like to avoid a sentinel symbol.

**Comment by kriskowal** [comment]
cc @patrick-soquet, `'*'` is not a reserved module export name, so we need another binding form.

**Comment by Jack-Works** [comment]
> I do not see how that conclusion follows from https://github.com/tc39/ecma262/pull/2154.

Consider this code:


```js
import { "*" as x } from 'mod'
```

**Comment by patrick-soquet** [comment]
Considering that star binding is common and that star-named binding is uncommon, maybe it is the named case that should require a special descriptor? Something like
```
{ importNamed: "*", as: "x", from:"mod" }
{ exportNamed: "*", as: "x", from:"mod" }
```
Or, considering that the `initialize` function would have to use `["*"]` to access the star-named binding, something like:
```
{ import: ["*"], as: "x", from:"mod" }
{ export: ["*"], as: "x", from:"mod" }
```
These JSON serializable forms would work with any string of course.

**Comment by Jack-Works** [comment]
Or

```json
bindings: [{
    from: 'mod',
    import: [
        { namespace: true, as: "x" },
        { import: "x", as: "y" }
    ],
    export: [ ... ]
}]
```

**Comment by kriskowal** [comment]
I like @patrick-soquet’s suggestion, having independently arrived at the same conclusion.

```
  // import * as X from 'X';
  { importAllFrom: string, as: string } |

  // export * from 'X';
  // export * as X from 'X';
  { exportAllFrom: string, as?: string };
```

**Comment by kriskowal** [comment]
Champions, please leave your 👍 or 👎 reactions on @patrick-soquet’s suggestion above or just stamp #66. I’ve revised the PR to reflect the `importAllFrom` and `exportAllFrom` forms.

**Comment by Jack-Works** [comment]
@kriskowal I suggest merging all import/re-exports from the same import spec (means you don't have to repeat URLs). This will make bindings smaller and still reserve the import order

**Comment by kriskowal** [comment]
Do you mean to make the bindings array more closely resemble the AST for the import and export statements? When it comes to the implications for a native implementation, I defer to @patrick-soquet who has made a bindings array like this work in XS. What do you think, Patrick?

**Comment by Jack-Works** [comment]
> Do you mean to make the bindings array more closely resemble the AST for the import and export statements? When it comes to the implications for a native implementation, I defer to @patrick-soquet who has made a bindings array like this work in XS. What do you think, Patrick?

No, I mean something like this:

```js
bindings: [{
    from: 'mod',
    imports: [
        { namespace: true, as: "x" },
        { import: "x", as: "y" }
    ],
    exports: [ ... ]
}]
```

If you import 10 things from "mod", it will be merged into a group so "mod" won't repeat.
